from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1204, 625)

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 112, 41))

        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UploadFile = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.UploadFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        sizePolicy.setHeightForWidth(self.UploadFile.sizePolicy().hasHeightForWidth())
        self.UploadFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UploadFile.setFont(font)
        self.UploadFile.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.UploadFile.setIcon(icon)
        self.UploadFile.setObjectName("UploadFile")
        self.horizontalLayout.addWidget(self.UploadFile)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 70, 731, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.showData = QtWidgets.QScrollArea(parent=self.gridLayoutWidget)
        self.showData.setWidgetResizable(True)
        self.showData.setObjectName("showData")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 727,
                                                               237))

        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ShowData = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.ShowData.setEnabled(False)
        self.ShowData.setGeometry(QtCore.QRect(0, 0, 731, 241))
        self.ShowData.setObjectName("ShowData")
        self.showData.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.showData, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 731, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.desc_data = QtWidgets.QScrollArea(parent=self.gridLayoutWidget_2)
        self.desc_data.setWidgetResizable(True)
        self.desc_data.setObjectName("desc_data")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 727,
                                                                 237))

        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Datadesc = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.Datadesc.setEnabled(True)
        self.Datadesc.setGeometry(QtCore.QRect(0, 0, 731, 241))
        self.Datadesc.setAccessibleDescription("")
        self.Datadesc.setObjectName("Datadesc")
        self.desc_data.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.desc_data, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(930, 70, 258, 31))

        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Test_Size = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_2)
        self.Test_Size.setEnabled(False)
        self.Test_Size.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Test_Size.setObjectName("Test_Size")
        self.horizontalLayout_2.addWidget(self.Test_Size)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(750, 70, 151, 35))

        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(750, 180, 131, 31))

        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(927, 180, 251, 31))

        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Alpha_Size = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_5)
        self.Alpha_Size.setEnabled(False)
        self.Alpha_Size.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Alpha_Size.setObjectName("Alpha_Size")
        self.horizontalLayout_6.addWidget(self.Alpha_Size)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(760, 230, 111, 151))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.MSE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.MSE.setEnabled(False)
        self.MSE.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.MSE.setFont(font)
        self.MSE.setObjectName("MSE")
        self.MAE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.MAE.setEnabled(False)
        self.MAE.setGeometry(QtCore.QRect(10, 70, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.MAE.setFont(font)
        self.MAE.setObjectName("MAE")
        self.RMSE = QtWidgets.QRadioButton(parent=self.groupBox)
        self.RMSE.setEnabled(False)
        self.RMSE.setGeometry(QtCore.QRect(10, 120, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.RMSE.setFont(font)
        self.RMSE.setObjectName("RMSE")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(780, 400, 101, 41))

        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.train = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.train.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        sizePolicy.setHeightForWidth(self.train.sizePolicy().hasHeightForWidth())
        self.train.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.train.setFont(font)
        self.train.setObjectName("train")
        self.horizontalLayout_7.addWidget(self.train)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(780, 500, 101, 41))

        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.test = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.test.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        sizePolicy.setHeightForWidth(self.test.sizePolicy().hasHeightForWidth())
        self.test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test.setFont(font)
        self.test.setObjectName("test")
        self.horizontalLayout_8.addWidget(self.test)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(920, 400, 258, 31))

        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.train_error = QtWidgets.QPlainTextEdit(parent=self.horizontalLayoutWidget_8)
        self.train_error.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        sizePolicy.setHeightForWidth(self.train_error.sizePolicy().hasHeightForWidth())
        self.train_error.setSizePolicy(sizePolicy)
        self.train_error.setAccessibleDescription("")
        self.train_error.setUndoRedoEnabled(False)
        self.train_error.setObjectName("train_error")
        self.horizontalLayout_9.addWidget(self.train_error)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(920, 500, 258, 31))

        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.test_error = QtWidgets.QPlainTextEdit(parent=self.horizontalLayoutWidget_9)
        self.test_error.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        sizePolicy.setHeightForWidth(self.test_error.sizePolicy().hasHeightForWidth())
        self.test_error.setSizePolicy(sizePolicy)
        self.test_error.setUndoRedoEnabled(False)
        self.test_error.setObjectName("test_error")
        self.horizontalLayout_10.addWidget(self.test_error)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(1010, 110, 131, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Test_Volume = QtWidgets.QLabel(parent=self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Test_Volume.setFont(font)
        self.Test_Volume.setObjectName("Test_Volume")
        self.gridLayout_3.addWidget(self.Test_Volume, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(1000, 220, 141, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Alpha_Volume = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Alpha_Volume.setFont(font)
        self.Alpha_Volume.setObjectName("Alpha_Volume")
        self.gridLayout_4.addWidget(self.Alpha_Volume, 0, 0, 1, 1)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UploadFile.setText(_translate("Dialog", "Choose File"))
        self.label.setText(_translate("Dialog", "Test Size"))
        self.label_3.setText(_translate("Dialog", "Alpha Size"))
        self.MSE.setText(_translate("Dialog", "MSE"))
        self.MAE.setText(_translate("Dialog", "MAE"))
        self.RMSE.setText(_translate("Dialog", "RMSE"))
        self.train.setText(_translate("Dialog", "Train"))
        self.test.setText(_translate("Dialog", "Test"))
        self.Test_Volume.setText(_translate("Dialog", "Value: 0"))
        self.Alpha_Volume.setText(_translate("Dialog", "Value: 0"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
